/* Copyright 2021 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"

#define LAYOUT( \
     K01,  K14,K13,K73,K03, K0E, K08,K76,K16, K1E,K3E, K3D,K3B, K1D,K3C,K3F,K1F, \
     K11, K31, K34, K33, K35, K15, K12, K32, K38, K36, K37, K17, K18, K7E,       \
     K71,   K21, K24, K23, K25, K75, K72, K22, K28, K26, K27, K77, K78, K4E,     \
     K74,    K41, K44, K43, K45, K05, K02, K42, K48, K46, K47, K07, K5E,         \
     K70,       K51, K54, K53, K55, K65, K62, K52, K58, K56, K67, K50,           \
     K4C, K19,  K7B, K0A, K6E,                     K6A, K4F, K59, K5F,K0C, K6F,  \
    K6C, K6D, K6B \
) { \
    { KC_NO, K01,   K02,   K03,   KC_NO, K05,   KC_NO, K07,   K08,   KC_NO, K0A,   KC_NO, K0C,   KC_NO, K0E,   KC_NO }, \
    { KC_NO, K11,   K12,   K13,   K14,   K15,   K16,   K17,   K18,   K19,   KC_NO, KC_NO, KC_NO, K1D,   K1E,   K1F   }, \
    { KC_NO, K21,   K22,   K23,   K24,   K25,   K26,   K27,   K28,   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO }, \
    { KC_NO, K31,   K32,   K33,   K34,   K35,   K36,   K37,   K38,   KC_NO, KC_NO, K3B,   K3C,   K3D,   K3E,   K3F   }, \
    { KC_NO, K41,   K42,   K43,   K44,   K45,   K46,   K47,   K48,   KC_NO, KC_NO, KC_NO, K4C,   KC_NO, K4E,   K4F   }, \
    { K50,   K51,   K52,   K53,   K54,   K55,   K56,   KC_NO, K58,   K59,   KC_NO, KC_NO, KC_NO, KC_NO, K5E,   K5F   }, \
    { KC_NO, KC_NO, K62,   KC_NO, KC_NO, K65,   KC_NO, K67,   KC_NO, KC_NO, K6A,   K6B,   K6C,   K6D,   K6E,   K6F   }, \
    { K70,   K71,   K72,   K73,   K74,   K75,   K76,   K77,   K78,   KC_NO, KC_NO, K7B,   KC_NO, KC_NO, K7E,   KC_NO }, \
}

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/

